export enum Role {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  EDITOR = "EDITOR",
  VIEWER = "VIEWER",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum Permission {
  MANAGE_STORE = "MANAGE_STORE",
  DELETE_STORE = "DELETE_STORE",
  TRANSFER_OWNERSHIP = "TRANSFER_OWNERSHIP",

  VIEW_USERS = "VIEW_USERS",
  INVITE_USER = "INVITE_USER",
  REMOVE_USER = "REMOVE_USER",
  MANAGE_USERS = "MANAGE_USERS",

  VIEW_PRODUCTS = "VIEW_PRODUCTS",
  CREATE_PRODUCTS = "CREATE_PRODUCTS",
  EDIT_PRODUCTS = "EDIT_PRODUCTS",
  DELETE_PRODUCTS = "DELETE_PRODUCTS",

  VIEW_CATEGORIES = "VIEW_CATEGORIES",
  CREATE_CATEGORIES = "CREATE_CATEGORIES",
  EDIT_CATEGORIES = "EDIT_CATEGORIES",
  DELETE_CATEGORIES = "DELETE_CATEGORIES",

  VIEW_ORDERS = "VIEW_ORDERS",
  MANAGE_ORDERS = "MANAGE_ORDERS",

  VIEW_BILLBOARDS = "VIEW_BILLBOARDS",
  CREATE_BILLBOARDS = "CREATE_BILLBOARDS",
  EDIT_BILLBOARDS = "EDIT_BILLBOARDS",
  DELETE_BILLBOARDS = "DELETE_BILLBOARDS",

  VIEW_SIZES = "VIEW_SIZES",
  CREATE_SIZES = "CREATE_SIZES",
  EDIT_SIZES = "EDIT_SIZES",
  DELETE_SIZES = "DELETE_SIZES",

  VIEW_COLORS = "VIEW_COLORS",
  CREATE_COLORS = "CREATE_COLORS",
  EDIT_COLORS = "EDIT_COLORS",
  DELETE_COLORS = "DELETE_COLORS",

  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  VIEW_SALES = "VIEW_SALES",

  VIEW_PAGES = "VIEW_PAGES",
  CREATE_PAGES = "CREATE_PAGES",
  EDIT_PAGES = "EDIT_PAGES",
  DELETE_PAGES = "DELETE_PAGES",

  VIEW_BLOGS = "VIEW_BLOGS",
  CREATE_BLOGS = "CREATE_BLOGS",
  EDIT_BLOGS = "EDIT_BLOGS",
  DELETE_BLOGS = "DELETE_BLOGS",

  VIEW_FORMS = "VIEW_FORMS",
  CREATE_FORMS = "CREATE_FORMS",
  EDIT_FORMS = "EDIT_FORMS",
  DELETE_FORMS = "DELETE_FORMS",

  
}

export type RolePermissions = {
  [key in Role]: Permission[]
}

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.OWNER]: Object.values(Permission),
  [Role.SUPER_ADMIN]: Object.values(Permission),
  [Role.ADMIN]: [
    Permission.VIEW_PRODUCTS,
    Permission.CREATE_PRODUCTS,
    Permission.EDIT_PRODUCTS,
    Permission.MANAGE_ORDERS,
    Permission.VIEW_CATEGORIES,
    Permission.CREATE_CATEGORIES,
    Permission.EDIT_CATEGORIES,
    Permission.VIEW_ORDERS,
    Permission.VIEW_USERS,
    Permission.VIEW_PAGES,
    Permission.CREATE_PAGES,
    Permission.EDIT_PAGES,
    Permission.DELETE_PAGES,
    Permission.VIEW_BLOGS,
    Permission.CREATE_BLOGS,
    Permission.EDIT_BLOGS,
    Permission.DELETE_BLOGS,
    Permission.VIEW_FORMS,
    Permission.CREATE_FORMS,
    Permission.EDIT_FORMS,
    Permission.DELETE_FORMS,
  ],
  [Role.EDITOR]: [
    Permission.VIEW_PRODUCTS,
    Permission.CREATE_PRODUCTS,
    Permission.EDIT_PRODUCTS,
    Permission.VIEW_CATEGORIES,
  ],
  [Role.VIEWER]: [Permission.VIEW_PRODUCTS, Permission.VIEW_CATEGORIES, Permission.VIEW_ORDERS],
}
